name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, chromium, firefox, electron]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npx cypress run --browser ${{ matrix.browser }}

      # Eklenen bölüm: Testler başarısız olduğunda ekran görüntülerini ve videoları arşivle
      - name: Archive Cypress screenshots and videos
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: cypress-artifacts-${{ matrix.browser }}
          path: |
            cypress/screenshots/
            cypress/videos/
