name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
      - name: Run Cypress tests on Chrome
        run: npx cypress run --browser chrome
      - name: Run Cypress tests on Firefox
        run: npx cypress run --browser firefox


      # Eklenen bölüm: Testler başarısız olduğunda ekran görüntülerini ve videoları arşivle
      - name: Archive Cypress screenshots and videos
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots/
            cypress/videos/
